---
deployment:
 tasks:
 - export DEPLOYPATH=/home1/pixelwhi/public_html/innovatr.ai/
 - /bin/mkdir -p $DEPLOYPATH
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp index-v2.html $DEPLOYPATH
 - /bin/cp thank-you.html $DEPLOYPATH
 - /bin/cp contact.php $DEPLOYPATH
 - /bin/cp -R assets $DEPLOYPATH
